### ISSUE TITLE
package.json missing

### ISSUE THREAD

**Issue by Surojit-KB** [Twopersonwork/LinkedIn-Clone-React#33]
Hey guys, wanted to try out your app for a project. Couldn't run the frontend since the package.json is missing and installing the npm dependencies is not possible...

**Comment by arcee123** [comment]
request package.json

**Comment by prachijpatel** [comment]
Thank you guys for raising this issue, we will soon update it. We apologize for this inconvenience.

**Comment by prachijpatel** [comment]
Please find the latest package.json (2021)
